# Generated by Django 3.2.8 on 2021-10-10 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='adress',
        ),
        migrations.AddField(
            model_name='address',
            name='formatted_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='place_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
