# Generated by Django 3.2.8 on 2021-10-11 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryapp', '0002_auto_20211010_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='address',
        ),
        migrations.AddField(
            model_name='timeslot',
            name='address',
            field=models.ManyToManyField(blank=True, null=True, to='deliveryapp.Address'),
        ),
    ]
