# Generated by Django 3.2.8 on 2021-10-11 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryapp', '0003_auto_20211011_1240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=32)),
                ('status', models.CharField(max_length=8)),
                ('timeslot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deliveryapp.timeslot')),
            ],
        ),
    ]
